name: advert-workflow

on:
push:
branches: [ "Dev" ]
workflow_dispatch:
jobs:
build-and-push:
runs-on: ubuntu-latest
name: containerise-model
steps:
- name: 1. Checkout Repository
uses: actions/checkout@v4

- name: 2. Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.9'

- name: 3. Install dependencies
run: |
pip install -r requirements.txt
pip install pytest

- name: 4. Set up Docker Buildx
uses: docker/setup-buildx-action@v3

- name: 5. Log in to Docker Hub
uses: docker/login-action@v3
with:
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}

- name: 6. Build and Push Docker Image
uses: docker/build-push-action@v5
with:
context: .
file: Dockerfile
push: true
tags: |
${{ secrets.DOCKER_USERNAME }}/advertising:latest
${{ secrets.DOCKER_USERNAME }}/advertising:${{ github.sha }}
deploy-to-minikube:
runs-on: ubuntu-latest
name: pull-image-job
needs: build-and-push
steps:
- name: 1. Checkout Repository
uses: actions/checkout@v4

- name: 2. List files in the repository (for debugging)
run: |
echo "Current directory: $(pwd)"
echo "Listing all files..."
ls -R .

- name: 3. Set up and Start Minikube
uses: medyagh/setup-minikube@latest

- name: 4. Update Deployment with new Image Tag
run: |
sed -i "s|__IMAGE_NAME__|${{ env.DOCKER_IMAGE }}:${{ needs.build-and-push.outputs.image_tag }}|g" deployment.yaml
echo "--- Updated deployment.yaml (deployment.yaml) ---"
cat deployment.yaml

- name: 5. Deploy Application to Minikube
run: |
echo "Applying Kubernetes manifests..."
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml

- name: 6. Verify Deployment
run: |
echo "Waiting for deployment to be ready..."
kubectl rollout status deployment/score-deployment --timeout=120s
echo -e "\n--- Pod Status ---"
kubectl get pods
echo -e "\n--- Service Status ---"
kubectl get service
- name: 7. Start Background Services
run: |
# Requirement: Minikube Tunnel
nohup minikube tunnel > tunnel.log 2>&1 &

- name: 8. Rerun the services
run: |
#rerunning the serivces
echo -e "\n--- Service---"
kubectl get service

